/* global mergeInto, LibraryManager */
mergeInto(LibraryManager.library, {
  /* eslint-disable no-unused-vars */
  _wasm_accept__host: true,
  _wasm_accept: 'tizentvwasm.SocketsHostBindings.accept',
  _wasm_bind__host: true,
  _wasm_bind: 'tizentvwasm.SocketsHostBindings.bind',
  _wasm_close__host: true,
  _wasm_close: 'tizentvwasm.SocketsHostBindings.close',
  _wasm_connect__host: true,
  _wasm_connect: 'tizentvwasm.SocketsHostBindings.connect',
  _wasm_getpeername__host: true,
  _wasm_getpeername: 'tizentvwasm.SocketsHostBindings.getPeerName',
  _wasm_getsockname__host: true,
  _wasm_getsockname: 'tizentvwasm.SocketsHostBindings.getSockName',
  _wasm_getsockopt__host: true,
  _wasm_getsockopt: 'tizentvwasm.SocketsHostBindings.getSockOpt',
  _wasm_listen__host: true,
  _wasm_listen: 'tizentvwasm.SocketsHostBindings.listen',
  _wasm_poll__host: true,
  _wasm_poll: 'tizentvwasm.SocketsHostBindings.poll',
  _wasm_recv__host: true,
  _wasm_recv: 'tizentvwasm.SocketsHostBindings.recv',
  _wasm_recvfrom__host: true,
  _wasm_recvfrom: 'tizentvwasm.SocketsHostBindings.recvFrom',
  _wasm_recvmsg__host: true,
  _wasm_recvmsg: 'tizentvwasm.SocketsHostBindings.recvMsg',
  _wasm_select__host: true,
  _wasm_select: 'tizentvwasm.SocketsHostBindings.select',
  _wasm_send__host: true,
  _wasm_send: 'tizentvwasm.SocketsHostBindings.send',
  _wasm_sendmsg__host: true,
  _wasm_sendmsg: 'tizentvwasm.SocketsHostBindings.sendMsg',
  _wasm_sendto__host: true,
  _wasm_sendto: 'tizentvwasm.SocketsHostBindings.sendTo',
  _wasm_setsockopt__host: true,
  _wasm_setsockopt: 'tizentvwasm.SocketsHostBindings.setSockOpt',
  _wasm_shutdown__host: true,
  _wasm_shutdown: 'tizentvwasm.SocketsHostBindings.shutdown',
  _wasm_socket__host: true,
  _wasm_socket: 'tizentvwasm.SocketsHostBindings.create',
  /* eslint-enable no-unused-vars */
});
